name: 'Mihari'
description: 'A GitHub Action to run Mihari'
author: 'ninoseki'
inputs:
  command:
    description: 'command'
    required: true
    default: 'help'
  input:
    description: 'input (query, etc.)'
    required: false
  options:
    description: 'options (tags, etc.)'
    required: false
outputs:
  result:
    description: 'result'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }} ${{ inputs.input }} ${{ inputs.options }}