on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  mihari_job:
    runs-on: ubuntu-latest
    name: A job to run Mihari
    steps:
    - name: Run Mihari
      id: mihari
      uses: ninoseki/mihari-actionp@master
      with:
        mihari-command: 'shodan'
        mihari-argument: 'hostname:one.one.one.one'
    - name: Get the output
      run: echo "${{ steps.mihari.outputs.mihari-result }}"