name: Mihari

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  mihari_job:
    runs-on: ubuntu-latest
    name: A job to run Mihari
    steps:
    - name: Run Mihari
      id: mihari
      uses: ninoseki/mihari-action@main
      with:
        command: 'shodan'
        input: 'hostname:one.one.one.one'
        options: '--tag test'
    - name: Get the output
      run: echo "${{ steps.mihari.outputs.mihari-result }}"